name: ox_system_task
description: Ox System task by Abbos Donaboyev

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0
  intl: ^0.17.0
  alice: ^0.2.4
  flash: ^2.0.1
  get_it: ^7.2.0
  shimmer: ^2.0.0
  auto_route: ^2.3.2
  flutter_svg: ^0.22.0
  flutter_bloc: ^7.2.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  json_annotation: ^4.1.0
  keyboard_dismisser: ^2.0.0
  shared_preferences: ^2.0.7
  freezed_annotation: ^0.14.2
  modal_bottom_sheet: ^2.0.0
  cached_network_image: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/